export const details = {

    hazardous: `A potentially hazardous asteroid is a near-Earth object with an orbit that can make close approaches to the Earth and large enough to cause significant regional damage in the event of impact.`,
    sentry: `Sentry is a highly automated collision monitoring system that continually scans the most current asteroid catalog for possibilities of future impact with Earth over the next 100 years.`,
    orbBody: 'In astrodynamics, an orbiting body is any physical body that orbits a more massive one, called the primary body. The orbiting body is properly referred to as the secondary body, which is less massive than the primary body.',
    orbDetDate: 'Orbit determination is the estimation of orbits of objects such as moons, planets, and spacecraft. One major application is to allow tracking newly observed asteroids and verify that they have not been previously discovered.',
    arc: 'In observational astronomy, the observation arc (or arc length) of a solar system body is the time period between its earliest and latest observations, used for tracing the body\'s path. It is usually given in days or years. The term is mostly used in the discovery and tracking of asteroids and comets. Arc length has the greatest influence on the accuracy of an orbit. The number and spacing of intermediate observations has a lesser effect.',
    orbUncert: 'The uncertainty parameter U is a parameter introduced by the Minor Planet Center (MPC) to quantify concisely the uncertainty of a perturbed orbital solution for a minor planet. The parameter is a logarithmic scale from 0 to 9 that measures the anticipated longitudinal uncertainty in the minor planet\'s mean anomaly after 10 years. The larger the number, the larger the uncertainty. The uncertainty parameter is also known as condition code in JPL\'s Small-Body Database Browser. The U value should not be used as a predictor for the uncertainty in the future motion of near-Earth objects.',
    minOrbIntersect: 'Minimum orbit intersection distance (MOID) is a measure used in astronomy to assess potential close approaches and collision risks between astronomical objects. It is defined as the distance between the closest points of the osculating orbits of two bodies. Of greatest interest is the risk of a collision with Earth.',
    tisserand: 'Tisserand\'s parameter (or Tisserand\'s invariant) is a value calculated from several orbital elements (semi-major axis, orbital eccentricity and inclination) of a relatively small object and a larger "perturbing body". It is used to distinguish different kinds of orbits.',
    epochOscul: 'The instant of time at which the position and velocity vectors are specified is the epoch of osculation. The osculating orbit touches (“kisses”) the real, perturbed orbit at the epoch of osculation. The verb “to osculate”, from the Latin osculare, means “to kiss”.',
    eccintricity: 'The eccentricity of an elliptical orbit is a measure of the amount by which it deviates from a circle; it is found by dividing the distance between the focal points of the ellipse by the length of the major axis. ',
    semiMajorAxis: 'The semi-major axis (major semiaxis) is the longest semidiameter or one half of the major axis, and thus runs from the centre, through a focus, and to the perimeter. The semi-minor axis (minor semiaxis) of an ellipse or hyperbola is a line segment that is at right angles with the semi-major axis and has one end at the center of the conic section. For the special case of a circle, the lengths of the semi-axes are both equal to the radius of the circle. Together with the semi-minor axis , b, and eccentricity, e, it forms a set of related values that completely describe the shape of an ellipse.',
    inclination: 'Orbital inclination measures the tilt of an object\'s orbit around a celestial body. It is expressed as the angle between a reference plane and the orbital plane or axis of direction of the orbiting object.',
    ascNodeLgtd: 'The longitude of the ascending node (☊ or Ω) is one of the orbital elements used to specify the orbit of an object in space. It is the angle from a specified reference direction, called the origin of longitude, to the direction of the ascending node, as measured in a specified reference plane.',
    orbPeriod: 'The orbital period is the time a given astronomical object takes to complete one orbit around another object, and applies in astronomy usually to planets or asteroids orbiting the Sun, moons orbiting planets, exoplanets orbiting other stars, or binary stars.',
    perihelionDist: 'The perihelion is the point in the orbit of a planet, asteroid or comet that is nearest to the sun.  The word perihelion stems from the Greek words "peri," meaning near, and "Helios," meaning the Greek god of the sun.',
    perihelionArg: 'Angle ω (called the argument of perihelion) is the angular distance from the ascending node to the perihelion measured in the orbit plane.',
    aphelionDist: 'Aphelion, in astronomy, the point in the orbit of a planet, comet, or other body most distant from the Sun. It is the opposite of perihelion, which is the point that is nearest to the sun.',
    perihilionTime: 'Any date at which the object in orbit was known to be at perihelion',
    meanAnomaly: 'In celestial mechanics, the mean anomaly is the fraction of an elliptical orbit\'s period that has elapsed since the orbiting body passed periapsis, expressed as an angle which can be used in calculating the position of that body in the classical two-body problem.',
    meanMotion: 'In orbital mechanics, mean motion is the angular speed required for a body to complete one orbit, assuming constant speed in a circular orbit which completes in the same time as the variable speed, elliptical orbit of the actual body.',
    equinox: 'Equinox, either of the two moments in the year when the Sun is exactly above the Equator and day and night are of equal length; also, either of the two points in the sky where the ecliptic (the Sun\'s annual pathway) and the celestial equator intersect.',
    orbClassType: ` AMO is referring to Amor asteroids: near-Earth asteroids. The orbital perihelion of these objects is close to, but greater than, the orbital aphelion of Earth (a > 1.0 AU and 1.017 AU < q < 1.3 AU).
        
    APO is referring to Apollo asteroids: near-Earth asteroid orbits which cross the Earth's orbit (a > 1.0 AU and q < 1.017 AU).
        
    ATE is referring to Aten asteroids: dynamical group of asteroids whose orbits bring them into proximity with Earth. By definition, Atens are Earth-crossing asteroids (a<1.0 AU and Q>0.983 AU).`
}